---
- name: Install Apache, MySQL, PHP
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apache2
    - mysql-server
    - php
    - libapache2-mod-php
    - php-mysql

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes

